### ISSUE TITLE
Apply to current tab only

### ISSUE THREAD

**Issue by JJRcop** [M-Reimer/languageswitch#14]
Like #4, but instead of saving settings per website and adding a configuration widget, feature a checkbox at the bottom of the menu that applies the change to the current tab only.

**Comment by M-Reimer** [comment]
And similar answer like in #4 then :stuck_out_tongue: 

Most probably out of scope for this Add-on. Reworking in a way like this would probably mean that much changes that a completely new Add-on would be the better way to keep this one at its current functionality and create the new one directly with "non global switching" in mind.

"Apply to current tab only" probably is even less useful compared to doing the switch "per domain" as every website can open new tabs or even you could open new tabs manually from this website. And migrating the setting from one tab to another probably could be pretty tricky.

**Comment by M-Reimer** [comment]
Adding any way to make something that is **not** a global setting change would **heavily** increase the codebase of my Add-on.

The goal of **this** Add-on is to provide a global switch of the preferred language which is communicated to websites. It was never the plan to provide any kind of "per site" or "per tab" switching. With a functionality like this in mind the whole Add-on would have to be developed in a different way, so to make something like this it would be better to start from scratch and create the whole backend with either "per site" or "per tab" switching in mind.

AND MOST IMPORTANT: I don't plan to do this.
