### ISSUE TITLE
dispatch languagechange event

### ISSUE THREAD

**Issue by noelmace** [M-Reimer/languageswitch#16]
Changing the preferred language with Language Switch doesn't lead to any [`languagechange` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/languagechange_event).

> From the [HTML standard](https://html.spec.whatwg.org/multipage/indices.html#event-languagechange): «Fired at the global scope object when the user's preferred languages change.»

It is therefore necessary to set Language Switch language to "default", and then to change the "real" `NavigatorLanguage` via `intl.accept_languages` in Firefox to test this kind of feature.

 I never contributed to a Firefox extension, but I would be happy to help implement this feature.

**Comment by M-Reimer** [comment]
I've never read anything about this event. But for proper language switch testing, it will be a good idea to add this.

I have not found a good test page on the web to test out this event. I think it's time to create my own test page then.

Implementing this could be tricky but I already think I know a way to properly add this.

**Comment by M-Reimer** [comment]
Fixed in current GIT state. Feel free to test this out.

**Comment by noelmace** [comment]
LGTM. Thx
