### ISSUE TITLE
Does not work with Firefox 90.0.2 !

### ISSUE THREAD

**Issue by Nokia808** [M-Reimer/languageswitch#17]
Hi.

This add-on no more work with firefox 87.0 ! 

I'm on Fedora Linux 32 X64 bit Cinnamon edition, & my firefox installed from official Fedora repositories ....

Best.

**Comment by M-Reimer** [comment]
Can not reproduce. Please describe more in detail how you verified that it does not work.

**Comment by M-Reimer** [comment]
No further feedback --> Closing

**Comment by Nokia808** [comment]
Hello ! Sorry for my delay ! 

Dear this add-on do not working on my Firefox version 90.0.2 installed from official repositories of my Fedora 34 X64 Cinnamon edition ! I tried multiple pages each of them support different languages .... What ever I changed language, it will remain sticky on default Firefox built-in setting which is currently en-US (1st choice). I'm Arabic tongue. I'm already added "Arabic" (ar) to my Firefox built-in setting. Language displacement priorities are:

en-Us
en
ar

I'm already added "Arabic" to the add on, so that it's code is:
ar,en-US,en

I tested:
https://aliexpress.com
https://www.france24.com
https://www.bbc.com
& many other sites with same failure result ! When I set to "Arabic" the page will appear in English (even after restarting my Firefox) !

I tried "French" with same error.

Kindly, re-open this issue & investigate about it.

**Comment by M-Reimer** [comment]
I'll check with the pages you suggested.

Did You try with just the Firefox language settings already (move "ar" to the top). Does it work then?

**Comment by M-Reimer** [comment]
Oh. Forgot to ask: Do you use "private browsing mode" and if so: Did you allow my Add-on to run there?

**Comment by Nokia808** [comment]
@M-Reimer 
Hello !
1) I'm already give your add-on permission to work in private browsing mode,
2) this issue happening in both private & non-private modes,
3) but it seem now that error not in your add-on ! But in the Firefox itself !! I tried to change built-in setting of my Firefox, so that preferred page language set 1st to Arabic. But same error happened as if I'm still set on English-US (original 1st choice) ! I tried to set French as 1st choice, but also same error happened & English page opened to me not French !

**Comment by M-Reimer** [comment]
I'll check as soon as possible but for me it seems like the websites, you mentioned, just don't care about the preferred language sent by the browser.

**Comment by Nokia808** [comment]
I tested same pages on my Android Firefox (not installed your add-on on it) & my mobile language setting is on Arabic, but web sites open on English version ! I checked "language" setting of my Android Firefox & it is on system default (which mean Arabic) !

I do not know more. But what I'm very sure from, like that I'm sure from my name, is that all these wevb sites were behave differently before version 87.0 of Firefox !

**Comment by M-Reimer** [comment]
It does work with your example https://www.france24.com/

And it will switch to "Arabic" language with the language string "ar,en-US,en". So the functionality works. It just heavily depends on the websites to correctly support it. That's also the main purpose of my Add-on. It is meant for developers to easily check theirs websites for correct language switching based on the browser language.
