### ISSUE TITLE
navigator.languages order is not changed

### ISSUE THREAD

**Issue by testuser7** [M-Reimer/languageswitch#2]
navigator.languages order is not changed (some websites are not working properly).

**Comment by M-Reimer** [comment]
Please describe your problem more in detail!
- What do you mean with "order"? "navigator.languages" doesn't have any "order". It's just one single language identifier
- Which websites are not working properly? (At least one example)

**Comment by testuser7** [comment]
If you configure webpage languages order
![web_lang](https://user-images.githubusercontent.com/10881063/48258664-f1faed00-e415-11e8-9fb3-92f2f2186a20.jpeg)
then you will get
`navigator.language
"en-US"`
`navigator.languages
Array(3) [ "en-US", "en", "de" ]`

After changing order
![web_lang_de](https://user-images.githubusercontent.com/10881063/48258879-85ccb900-e416-11e8-9590-b1cfc5dd5c09.jpeg)
you will get
`navigator.language
"de"`
`navigator.languages
Array(3) [ "de", "en-US", "en" ]`

**Comment by M-Reimer** [comment]
Thanks for the additional information.
I didn't even know about the existence of "navigator.languages" and thought you mean "navigator.language".
Please try the new version (1.3.0) and tell me if this fixes your issue. I hope "navigator.languages" support now works as it should.

**Comment by testuser7** [comment]
Thanks!
Now languages order is changed correctly.

**Comment by M-Reimer** [comment]
Thanks for your feedback.
