### ISSUE TITLE
Invalid header array: in Browser Console after restart and with language "Default"

### ISSUE THREAD

**Issue by aafbsd** [M-Reimer/languageswitch#21]
First, I am no web or addon developer so if this is all nonsense, feel free
to ignore it :-).

I am using 2.9.0 with esr-91. While debugging some other stuff, I noted the
following error in the Browser Console for each request:

Invalid header array: [{name:"Host", value:"www"}, {name:"User-Agent", value:"Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"}, {name:"Accept", value:"image/webp,*/*"}, {name:"Accept-Language", value:(void 0)}, {name:"Accept-Encoding", value:"gzip, deflate"}, {name:"DNT", value:"1"}, {name:"Connection", value:"keep-alive"}, {name:"Referer", value:"http://www/"}]
 
Please note the: name:"Accept-Language", value:(void 0)
 
I tracked it down to this extension. It happens if no specific language is
selected ("Default") and also never had been during the browser session.
As soon as you select any language and go back to "Default" the problem
is gone.
 
This reason might be that gAcceptLanguage is undefined (until it once
got set and possibly reset) but RewriteAcceptLanguage() only tests
if it's empty (and not if it is undefined). I fixed it here with:

```
--- background.js.ORI   2021-12-24 09:05:11.000000000 +0100
+++ background.js       2021-12-31 11:28:28.000000000 +0100
@@ -100,7 +100,7 @@
 
 // Header rewrite handler. Rewrites "Accept-Language".
 function RewriteAcceptLanguage(e) {
-  if (gAcceptLanguage != "") {
+  if (typeof gAcceptLanguage !== 'undefined' && gAcceptLanguage != "") {
     e.requestHeaders.forEach(function(header){
       if (header.name.toLowerCase() == "accept-language")
         header.value = gAcceptLanguage;
```

Another fix might be:

```
--- background.js.ORI   2021-12-24 09:05:11.000000000 +0100
+++ background.js       2021-12-31 11:58:38.386200000 +0100
@@ -1,5 +1,5 @@
 // Holds the current Accept-Language value
-let gAcceptLanguage;
+let gAcceptLanguage = "";

```

but I don't know if it might get undefined somewhere else...

**Comment by M-Reimer** [comment]
Had to search first why this actually happened. And it is some ugliness in Javascript. Actually kind of weird that this "===" actually is needed.

Thanks for the report.
