### ISSUE TITLE
Icon of the extension not showing up in toolbar after install

### ISSUE THREAD

**Issue by Lucas-C** [M-Reimer/languageswitch#23]
Hi!

I just tested your extension and after installing it on Firefox 125.0.3 (64 bits - Windows) from https://addons.mozilla.org/fr/firefox/addon/languageswitch/, nothing happened, no new icon appeared.

I tried to "customize the toolbar" but the icon of this extension is not listed.
I tried to restart the browser but nothing chenged.

The addon is correctly listed among the installed & active addons in my browser:
![Capture d'écran 2024-05-21 175928](https://github.com/M-Reimer/languageswitch/assets/925560/a2625301-4ad8-404b-a97e-7fdb91af3802)

**Comment by M-Reimer** [comment]
You have to access it from the Add-on menu. This is the puzzle piece icon in the toolbar.

For many use cases this is enough. If you still want it to be its own icon, you may choose "Pin to toolbar" from the context menu.

**Comment by Lucas-C** [comment]
I just checked and I confirm that it works fine!

Sorry for the trouble, and thank you for making & maintaining this addon 👍

As an humble suggestion, maybe adding a screenshot like this to the README.md and/or plugin page could be useful to other users:
![languageswitch-screenshot](https://github.com/M-Reimer/languageswitch/assets/925560/32153c3f-054b-4396-a6b7-27b4de5e04be)

**Comment by Lucas-C** [comment]
Thank you for your answer @M-Reimer!

I'm closing this now.
