### ISSUE TITLE
Makes the bookmark toolbar to disappear

### ISSUE THREAD

**Issue by riksoft** [M-Reimer/languageswitch#25]
It only happens since yesterday after Firefox Developer Edition upgrade itself to version 132.0b1 (64-bit) (Under Debian Bookworm).
The presence of the file {6e1ccc3a-6961-4b99-9455-e04cb868e7f9}.xpi into the extension folder, damages FF irreversibly. Even removing the addon FF won't fix the problem and FF won't show the toolbar anymore until it is refreshed from about:support creating a new profile.

To find the culprit I had to add all my addons 1 by 1  to the extension dir.

**Comment by riksoft** [comment]
I apologise... it's not this extension, it happens with **any addons** because the new version of Firefox 132 .0b1 (the last available today) has problems. I've blocked the auto-update and reinstalled the previous 131.0b9 from here
https://download-origin.cdn.mozilla.net/pub/devedition/releases/
and now everything works fine, including this wonderful extension.
So this non-bug is solved! :-)

**Comment by M-Reimer** [comment]
Thanks for the feedback
