### ISSUE TITLE
Save the selected language per domain

### ISSUE THREAD

**Issue by initseis** [M-Reimer/languageswitch#26]
It would be great if the add-on allowed us to save the selected language per domain. In my case, I use some websites in Spanish and others in English.

**Comment by M-Reimer** [comment]
Duplicate of https://github.com/M-Reimer/languageswitch/issues/4

If someone provides a well tested Pull Request, I would probably add this but I won't rework the whole Add-on myself.

**Comment by initseis** [comment]
Could you consider leaving this issue open? It might make it easier for others to find it and potentially contribute a well-tested Pull Request.

**Comment by M-Reimer** [comment]
Can you please check if this solves your issue?

https://addons.mozilla.org/de/firefox/addon/accept-language-per-site/

**Comment by initseis** [comment]
> Can you please check if this solves your issue?
> 
> https://addons.mozilla.org/de/firefox/addon/accept-language-per-site/

Not really, with that I have to type each domain (it is annoying). I would prefer an option in preferences "Save per domain" so it saves automatically the selected language per domain.
