### ISSUE TITLE
lang indicator on the icon

### ISSUE THREAD

**Issue by iocast** [M-Reimer/languageswitch#3]
Many thanks for the extension.
Is it possible to add something like a language overlay to the icon, so that you see, which language is selected?

**Comment by M-Reimer** [comment]
It is possible to put small text snippets over the icon. But what should I put there? The label can be way too long to be put there and the language string is too long either

**Comment by M-Reimer** [comment]
I only have a few (maximum 4) characters anyway so I think I'll put the language identifier of the highest priority language (leftmost)

**Comment by M-Reimer** [comment]
Fixed in 2.0.0
