### ISSUE TITLE
Can't able to change language.

### ISSUE THREAD

**Issue by DhimanAirao** [M-Reimer/languageswitch#5]
I added this plugin yesterday. I tried it on many different site but it didn't change language of any site.Help me how to use this extension in mozilla.

**Comment by M-Reimer** [comment]
It only works for websites that use the browser sent language. My Add-on modifies all common ways where websites can detect the browser language but not all websites make use of them.

Which websites did you try? "Google", for example, usually works well. It also works well on many Forum softwares.

It does **not** work on many "mozilla.org" domains as Mozilla does not allow Add-ons to run there.

**Comment by M-Reimer** [comment]
No more feedback. Closing.
